spring:
  datasource:
    url: jdbc:mysql://localhost:3306/knitly_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver